config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    collection do 
      get :search
      get :results
    end
  end
  
  resources :routes
  resources :attempts
  resources :comments
  resources :tags
  resources :ratings
  resources :friendships
  resources :posts
  resources :locations
  root 'posts#index'
 

  get "auth/facebook" => "auth#facebook"
  get "/auth/facebook/callback" => "auth#facebook"
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
	has_many :friendships
	has_many :friends, :through => :friendships
	belongs_to :role
	has_many :attempts
	has_many :comments
	has_many :ratings
	
	validates_presence_of :email
	validates_presence_of :user_name
	validates_uniqueness_of :email
	validates_uniqueness_of :user_name

	Paperclip.options[:command_path] = "/usr/local/bin/"
	
 	#search method
 	def self.search(params)
		user_name = params[:user_name]
    user_friend = params[:friend]
		search = User.all

		if user_name.present?
			 search = search.where('user_name Like ?', "#{user_name}")
		end

  
	end

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '50x50>',
    square: '200x200#',
    medium: '300x300>'
  }, :default_url => "default.png"


  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  #pull in info from facebook
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
   	 	user.provider = auth.provider
    	user.uid = auth.uid
    	if auth.info.nickname
    		user.user_name = auth.info.nickname
    	else
    		user.user_name = "#{auth.info.first_name}#{auth.info.last_name}"
    	end
    	user.first_name = auth.info.first_name
    	user.last_name = auth.info.last_name
    	
      # FIXME these were working before devise was implemented need to be fixed
      # user.facebook_image = auth.info.image
    	# user.oauth_token = auth.credentials.token
    	# user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    	if auth.extra.email
    		user.email = auth.extra.email
    	else
    		user.email = "email@example.com"
    	end
    	user.password = auth.info.last_name
    	user.save!
  	end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource param_method: :users_params
	skip_authorize_resource :only => :search
	
	def index
		@users = User.all.order('total_score DESC')
	end



	

	def show 
		@user = User.find(params[:id])
		@user.total_score = @user.attempts.sum(:attempt_score)
		@user.save
		@attempts = AttemptsPresenter.new(@user.attempts)
		@grade_names = @attempts.collect_grades
		@tag_names =@attempts.collect_tags
	end



	def search
		@search_results = User.search(params[:search])
		puts @search_results
		render results_users_path 
	end


	private

	def user_params
		params.require(:user).permit!
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.row
	
	.large-12.columns
		
		%h1 Users
		
		%table#users.display
			%thead
				%th image
				%th name
				%th score
				%th follow
			%tbody 
				- @users.each do |u|
					%tr
						%td
							= image_tag u.avatar.url ,:style => "max-width: 50px"
						%td	
							=link_to "#{u.user_name}", user_path(u)
						%td
							= u.total_score
						%td
							= link_to "Follow", friendships_path(:friend_id => u), :method => :post

app/views/users/results.html.haml
%br
.large-6.columns
	%h3 Search Users
	= form_tag search_users_path, method: "get" do
		= label_tag "user_name"
		= text_field_tag "search[user_name]"
		%br
		= submit_tag "search"



.large-6.columns
	%table
		%th
		%th name 
		%th score 
		- @search_results.each do |u|
			%tr
				%td
					= image_tag u.avatar.url ,:style => "max-width: 50px"
				%td	
					= u.user_name
				%td
					= u.total_score
				%td
					= link_to "Follow", friendships_path(:friend_id => u), :method => :post

app/views/users/show.html.haml
%br
.row
		
	/ Sidebar
	.large-3.columns
		
		
		%h1
			= @user.user_name
		
			= image_tag @user.avatar.url ,:style => "max-width: 300px"

		%h2 Scores
		%table.table-bordered
			%th today
			%th week
			%th month
			%th year
			%th total
			%tr 
				%td
					= @user.attempts.this_day.sum(:attempt_score)
				%td
					= @user.attempts.this_week.sum(:attempt_score)
				%td
					= @user.attempts.this_month.sum(:attempt_score)
				%td
					= @user.attempts.this_year.sum(:attempt_score)
				%td
					=  @user.attempts.sum(:attempt_score)
			


		


		%h2	Following
		-if current_user.id == @user.id
			=link_to "start following" , users_path



		.panel
			-@user.friends.each do |f|

				%span.has-tip{"data-tooltip" => "", title: "#{f.user_name}"} 
					= link_to "#{image_tag(f.avatar.url(:thumb), style:"max-width: 50px")}".html_safe, user_path(f)

	.large-8.columns
		%div{"data-magellan-expedition" => "fixed"}
			%dl.sub-nav
				%dd{"data-magellan-arrival" => "about"}
					%a{href: "#about"} About
				%dd{"data-magellan-arrival" => "attempts"}
					%a{href: "#attempts"} Attempts
				%dd{"data-magellan-arrival" => "charts"}
					%a{href: "#charts"} Charts
		%br

		%a{name: "about"}
		%h3{"data-magellan-destination" => "about"} About
		.panel
			%p 
				=@user.description
		%a{name: "attempts"}
		%h3{"data-magellan-destination" => "attempts"} Latest Attempts
		.panel
			%p
				- if current_user.id == @user.id
					=link_to "(add a new attempt)", new_attempt_path
					=link_to "(view all your attempts)", attempts_path
				%table
					%th date
					%th score
					%th route
					%th grade
					%th completed
					%th flash
					- @user.attempts.last(10).reverse.each do |f|
						%tr
							%td
								=formatted_date(f.date_attempted)
							%td
								=f.attempt_score
							
							%td
								-if f.route
									=link_to "#{f.route.name}", route_path(f.route.id)
									
								-else
									route not found
							%td
								-if f.route
									=f.route.grade.name
							%td
								=f.completed
							%td
								=f.flash
		
		%a{name: "charts"}
		%h3{"data-magellan-destination" => "charts"} Charts & Info
		.panel
			
			
			= pie_chart(@grade_names)
			%p
				grade of routes climbed
			
			
			= line_chart @user.attempts.group_by_day(:date_attempted , range: 1.weeks.ago.midnight..Time.now).count
			%p
				number of routes climbed this week

			= bar_chart(@tag_names)
			%p
				routes climbed are descriped as

			
			


				