config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    collection do 
      get :search
      get :results
    end
  end
  
  resources :routes
  resources :attempts
  resources :comments
  resources :tags
  resources :ratings
  resources :friendships
  resources :posts
  resources :locations
  root 'posts#index'
 

  get "auth/facebook" => "auth#facebook"
  get "/auth/facebook/callback" => "auth#facebook"
 
end

app/models/route.rb
class Route < ActiveRecord::Base
validates_presence_of :grade_id 
validates_presence_of :name
has_many :attempts
has_many :ratings
belongs_to :grade
belongs_to :location
has_many :comments, as: :commentable
has_and_belongs_to_many :tags


end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
	load_and_authorize_resource param_method: :routes_params
	def index 
		@routes = Route.all
	end

	def show
		@route = Route.find(params[:id])
		@new_comment = @route.comments.build
		@new_tag = @route.tags.build
		if current_user.present?
			if @route.ratings.where('user_id = ?', current_user.id)
				@new_rating = @route.ratings.build
			else
				@rating = @route.ratings.where('user_id = ?', current_user.id)
			end
		end
	end


	def new
		@new_route = Route.new
	end

	def create 
		@new_route = Route.new(route_params)

		if @new_route.save
			redirect_to routes_path, notice: "The new route has been added"
		else
			render new_route_path, notice: "you have failed to add this route"
		end
	end

	def edit 
		@route = Route.find(params[:id])
	end

	def update
		@route = Route.find(params[:id])
		if @route.update_attributes(route_params)
			redirect_to routes_path, notice: "the route has been updated"
		else
			render edit_route_path(@route.id), notice: "failed to update the path"
		end
	end






	private

	def route_params
		params.require(:route).permit!
	end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_routes.html.haml
.row
	.large-6.columns
		%label Route Name:
		=f.text_field :name
	.large-2.columns
		%label Grade:
		=f.select :grade_id , Grade.all.collect { |g| [g.name, g.id]} 
	.large-4.columns	
		%label Location:
		= f.select :location_id, Location.all.collect {|u| [u.name, u.id]}
.row
	.large-12.columns
		%label Info:
		=f.text_area :info
.row		
	.large-10.columns
	.large-2.columns
		=f.submit "Submit", class:"button"

app/views/routes/edit.html.haml
.row
	.large-12.columns
		=form_for @route, url: route_path do |f|
			%fieldset
				%legend
					Edit route
				= render "routes", f: f

app/views/routes/index.html.haml
.row
	
	.large-12.columns
		%h1 Routes

		=link_to "add a route", new_route_path
		%br
		%br
		%table#routes.display
			%thead
				%th name
				%th grade
				%th location
				%th rating
			%tbody
				-@routes.each do |r|
					%tr
						%td
							= link_to "#{r.name}", route_path(r) 
							
						%td
							= r.grade.name
						%td
							-if r.location
								= r.location.name
						%td 
							-if r.ratings
								=r.ratings.average(:rating)
		
	

		

app/views/routes/new.html.haml
.row
	.large-12-columns
		= form_for @new_route, url: routes_path do |f|
			%fieldset
				%legend 
					New route
				= render "routes", f: f

app/views/routes/show.html.haml
.row
	.large-9.columns
		%h1 
			= @route.name
		-if current_user
			-if current_user.role_id == 2

				= link_to "edit", edit_route_path
		
		%br
		%br
		.panel
			-if @route.location
				%p
					This route is located at:
					=link_to "#{@route.location.name}", location_path(@route.location) 
				%p
					= @route.info

		
		%h3 Comments
		.panel
		
			- @route.comments.each do |f|
				-if f.user
					.div{class:"label"}
						= f.user.user_name
					says:
					%br
					= f.content
					%hr
			-if current_user.present?
				%h6 Add a comment:
				= form_for @new_comment, url: comments_path, method: :post do |f|
					= f.hidden_field :commentable_id, value: @new_comment.commentable_id 
					= f.hidden_field :commentable_type, value: @new_comment.commentable_type
					= f.hidden_field :user_id, :value => current_user.id
					comment:
					%br
					= f.text_area :content
					= f.submit "submit", class: "button tiny"
			-else
				=link_to "Login to add a comment", login_path
	.large-3.columns
		%br
		%br
		.row
			.panel
				%h3
					Grade:
					= @route.grade.name
				
			
				
				%h3
					Rating:
					=@route.ratings.average(:rating)

				%h3
					Tags:
					%br
					-@route.tags.each do |f|
						-if f.name
							.label
								=f.name
			.panel
				-if current_user.present?
					- if @route.ratings.where('user_id = ?', current_user.id) == 1
						you already rated this!
						/ = form_for @new_rating, url: rating_path do |f|
						/ 	= f.hidden_field :user_id, :value => current_user.id
						/ 	= f.hidden_field :route_id, :value => @route.id
						/ 	= f.select :rating, options_for_select([[0, 0],[1, 1],[2,2],[3,3],[4,4],[5,5]]) 
						/ 	= f.submit "rate" , class:"button"
					- else
						= form_for @new_rating, url: ratings_path do |f|
							
							= f.hidden_field :user_id, :value => current_user.id
							= f.hidden_field :route_id, :value => @route.id
							.large-6.columns
								= f.select :rating, options_for_select([[0, 0],[1, 1],[2,2],[3,3],[4,4],[5,5]])
							.large-6.columns 
								= f.submit "rate" , class: "button tiny"
						
				
				
		

				= form_for @new_tag, url: tags_path, method: :post do |f|
					= hidden_field_tag :route_id, @route.id
					add tag:
					%br
					= f.text_field :name
					= f.submit "submit" , class: "button tiny"
					%br