config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    collection do 
      get :search
      get :results
    end
  end
  
  resources :routes
  resources :attempts
  resources :comments
  resources :tags
  resources :ratings
  resources :friendships
  resources :posts
  resources :locations
  root 'posts#index'
 

  get "auth/facebook" => "auth#facebook"
  get "/auth/facebook/callback" => "auth#facebook"
 
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :routes
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  has_many :comments, as: :commentable
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	load_and_authorize_resource param_method: :locations_params
	def index
		if params[:search].present?
			 @locations = Location.near(params[:search], params[:distance], order: 'distance')
			 @all = false
		else 
			@locations = Location.all
			@all = true
		end
	end

	def new
		@new_location = Location.new
	end

	def create
		@new_location = Location.new(location_params)
		if @new_location.save
			redirect_to locations_path
		else
			redirect_to new_location_path
		end
	end

	def show
		@location = Location.find(params[:id])
		@new_comment = @location.comments.build
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update_attributes(location_params)
			redirect_to locations_path
		else
			redirect_to edit_locations_path
		end
	end

	def destroy
		@location = Location.find(params[:id])
		@location.delete
		redirect_to locations_path
	end

	private

	def location_params
		params.require(:location).permit!
	end

	
end

app/views/locations/_locations.html.haml
%label name
= f.text_field :name
%label address
= f.text_area :address
%label rock type
= f.text_field :rock_type
%label description
= f. text_area :description
%label camping?
= f.check_box :camping
%br
= f.submit "submit", class:"button"

app/views/locations/edit.html.haml
.row
	.large-12.columns
		= form_for @location, url: location_path do |f|
			%fieldset
				%legend 
					Edit location
				= render "locations", f: f

app/views/locations/index.html.haml
.row
	.large-12.columns	
		%h1 Locations
		-if current_user
			-if current_user.role_id == 2
				%p
					= link_to "add a location" , new_location_path
				%br
		= form_tag locations_path, :method => :get do
			%fieldset
				%legend 
					Search for locations near:
				%label location
				= text_field_tag :search, params[:search]
				%label distance from: (in miles)
				= text_field_tag :distance, params[:distance], :value => 50
				= submit_tag "Search", :name => nil, class:"button"

		%table#locations.display
			%thead
				%tr
					%th name
					%th address
					%th camping
					%th rock type
					%th distance
			%tbody
				-@locations.each do |l|
					%tr
						%td
							= link_to "#{l.name}" , location_path(l)
						%td
							= l.address
						%td
							= l.camping
						%td
							= l.rock_type
						%td	
							- if @all == false
								= l.distance.round(2)
			

app/views/locations/new.html.haml
.large-12.columns
	= form_for @new_location, url: locations_path, method: :post do |f|
		%fieldset
			%legend 
				Add a new location
			= render "locations", f: f
	

app/views/locations/show.html.haml
.row
	.large-8.columns
		%h1 
			= @location.name
		-if current_user
			-if current_user.role_id == 2
				%p 
					=link_to "edit| ", edit_location_path(@location.id)
					=link_to " |delete" , location_path, :method => "delete"
					
		%ul.tabs{"data-tab" => ""}
			%li.tab-title.active
				%a{href: "#panel2-1"} About
			%li.tab-title
				%a{href: "#panel2-2"} Routes
		
		.tabs-content
			#panel2-1.content.active
				.panel
					%p
						= @location.description
					
			#panel2-2.content
				
			

				%br
				%table
					%th name
					%th grade
					%th rating
					%th view

					-@location.routes.each do |r|
						%tr
							%td
								-if r.name
									= r.name
							%td
								= r.grade.name
							%td
								
								=r.ratings.average(:rating)
							%td
								= link_to "view", route_path(r) 
								%br



		%h3 Comments
		.panel
			- @location.comments.each do |f|
				-if f.user
					.div{class:"label"}
						= f.user.user_name
					says:
					%br
					= f.content
					%hr
			- if current_user
				%h6 Add a comment:
				= form_for @new_comment, url: comments_path, method: :post do |f|
					= f.hidden_field :commentable_id, value: @new_comment.commentable_id 
					= f.hidden_field :commentable_type, value: @new_comment.commentable_type
					= f.hidden_field :user_id, :value => current_user.id
					comment:
					%br
					= f.text_area :content
					= f.submit "submit", class: "button"
			- else
				= link_to "login to comment", login_path
			

				
			
				
			
	/ Sidebar
	%br
	%br
	%br
	.large-4.columns
		%br
		= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=12&markers=#{@location.latitude}%2C#{@location.longitude}"
		%p
			%h5 Address:
			= @location.address

			

		

	


			