config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    collection do 
      get :search
      get :results
    end
  end
  
  resources :routes
  resources :attempts
  resources :comments
  resources :tags
  resources :ratings
  resources :friendships
  resources :posts
  resources :locations
  root 'posts#index'
 

  get "auth/facebook" => "auth#facebook"
  get "/auth/facebook/callback" => "auth#facebook"
 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
      user ||= User.new
     
      if user.role_id == 1
        can :manage, :all
      else
        can [:read], [Location, Post, Attempt, Grade, Route, User, Comment, Tag]
        can [:create], [Attempt, Route, User, Comment, Tag]
        can [:edit, :update], [Attempt, User, Comment, Tag]  
      end
  end
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
belongs_to :user
belongs_to :route
validates_presence_of :date_attempted

scope :this_day, -> {where('date_attempted = ?' , Date.today)}
scope :yesterday, -> {where('date_attempted = ?', Date.today - 1)}
scope :this_week, -> {where('date_attempted > ?', 7.days.ago)}
scope :last_week, -> {where('date_attempted >= ? AND date_attempted <= ?', 14.days.ago, 7.days.ago)}
scope :this_month, -> {where('date_attempted > ? ',   1.months.ago)}
scope :last_month, -> {where('date_attempted >= ? AND date_attempted <= ?', 2.months.ago, 1.months.ago )}
scope :this_year, -> {where('date_attempted > ? ',   1.years.ago)}
scope :last_year, -> {where('date_attempted >= ? AND date_attempted  <= ?', 2.years.ago,   1.years.ago)}

	# adds or subtracts points based on params provided
	def add_modifiers(grade, completed, flash)
	
			if completed == true
				if flash == true
						grade *= 1.5
				else
					grade
				end
			else
				grade *= 0.25
			end
			grade
		end




end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, polymorphic: :true
	validates_presence_of :content

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :routes
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :routes
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post <ActiveRecord::Base
belongs_to :user
validates_presence_of :user_id
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :route
	validates_uniqueness_of :route_id, :scope => [:user_id]
	


end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/route.rb
class Route < ActiveRecord::Base
validates_presence_of :grade_id 
validates_presence_of :name
has_many :attempts
has_many :ratings
belongs_to :grade
belongs_to :location
has_many :comments, as: :commentable
has_and_belongs_to_many :tags


end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_and_belongs_to_many :routes
validates_presence_of :name
validates_length_of :name, :maximum => 12
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
	has_many :friendships
	has_many :friends, :through => :friendships
	belongs_to :role
	has_many :attempts
	has_many :comments
	has_many :ratings
	
	validates_presence_of :email
	validates_presence_of :user_name
	validates_uniqueness_of :email
	validates_uniqueness_of :user_name

	Paperclip.options[:command_path] = "/usr/local/bin/"
	
 	#search method
 	def self.search(params)
		user_name = params[:user_name]
    user_friend = params[:friend]
		search = User.all

		if user_name.present?
			 search = search.where('user_name Like ?', "#{user_name}")
		end

  
	end

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '50x50>',
    square: '200x200#',
    medium: '300x300>'
  }, :default_url => "default.png"


  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  #pull in info from facebook
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
   	 	user.provider = auth.provider
    	user.uid = auth.uid
    	if auth.info.nickname
    		user.user_name = auth.info.nickname
    	else
    		user.user_name = "#{auth.info.first_name}#{auth.info.last_name}"
    	end
    	user.first_name = auth.info.first_name
    	user.last_name = auth.info.last_name
    	
      # FIXME these were working before devise was implemented need to be fixed
      # user.facebook_image = auth.info.image
    	# user.oauth_token = auth.credentials.token
    	# user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    	if auth.extra.email
    		user.email = auth.extra.email
    	else
    		user.email = "email@example.com"
    	end
    	user.password = auth.info.last_name
    	user.save!
  	end
	end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController


	def facebook
		user = User.from_omniauth(env['omniauth.auth'])
		session[:user_id] = user.id
		redirect_to root_url
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	load_and_authorize_resource param_method: :posts_params
	
	def index
		@posts = Post.order('post_date desc')
	end

	def new 
		@new_post = Post.new
	end


	def create
		@new_post = Post.new(post_params)
		if @new_post.save
			redirect_to posts_path
			
		else
			redirect_to :back
		end
	end

private

	def post_params
		params.require(:post).permit!
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	load_and_authorize_resource param_method: :tagss_params
	def new
		@new_tag = Tag.new
		@route = Route.new
	end

	def create
		@new_tag = Tag.new(tag_params)
		@route = Route.find(params[:route_id])
		if @new_tag.save
			@route.tags << @new_tag
			redirect_to :back
		else
			redirect_to :back
		end
	end

private

	def tag_params
		params.require(:tag).permit!

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource param_method: :users_params
	skip_authorize_resource :only => :search
	
	def index
		@users = User.all.order('total_score DESC')
	end



	

	def show 
		@user = User.find(params[:id])
		@user.total_score = @user.attempts.sum(:attempt_score)
		@user.save
		@attempts = AttemptsPresenter.new(@user.attempts)
		@grade_names = @attempts.collect_grades
		@tag_names =@attempts.collect_tags
	end



	def search
		@search_results = User.search(params[:search])
		puts @search_results
		render results_users_path 
	end


	private

	def user_params
		params.require(:user).permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

#helper to make dates display i want them to
	def formatted_date(date)
		date.strftime("%B %-d, %Y")
	end
		

# the next three methods makes devise login possible from non devise views
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
	%head
		%meta{:charset => "utf-8"}/
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%title= content_for?(:title) ? yield(:title) : "Boulder"
		= stylesheet_link_tag    "application"
		= javascript_include_tag "vendor/modernizr"
		= csrf_meta_tags
	%body

		
		
		%nav.top-bar{"data-topbar" => ""}
			%ul.title-area
				%li.name
					%h1
						%a{:href => "/posts"} ClimbTracker
				/ Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
				%li.toggle-topbar.menu-icon
					%a{:href => "#"}
						%span Menu
			%section.top-bar-section
				/ Right Nav Section
				%ul.right
					%li.active
						%a{:href => "#"}

							- if current_user
								= link_to "#{current_user.user_name}", user_path(current_user)
					%li.has-dropdown
						%a{:href => "#"} Menu
						%ul.dropdown
							%li
								%a{:href => "/routes"} Routes
							%li
								%a{:href => "/users"} Users
							%li
								%a{:href => "/locations"} Locations
							- if current_user.present?
								%li
									%a{:href => "/attempts"} My Attempts
								%li= link_to "Edit Profile", edit_user_registration_path
								%li
									- if current_user.role_id == 2
										%li
											%label admin
											%label/
										%li
											%a{:href => "/locations/new"} Add Location
										%li
											%a{:href => "/posts/new"} Add a new Post
				%ul.left
					%li
						- if current_user
							= link_to "Log out", destroy_user_session_path, :method => :delete
						- else
							/ = link_to "Log in", new_user_session_path
							%a{"data-reveal-id" => "myModal", :href => "#"} Log in

		#myModal.reveal-modal{"data-reveal" => ""}
			%h2 Log in
			= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
				%div
					= f.label :email
					%br/
					= f.email_field :email, autofocus: true
				%div
					= f.label :password
					%br/
					= f.password_field :password, autocomplete: "off"
				- if devise_mapping.rememberable?
					%div
						= f.check_box :remember_me
						= f.label :remember_me
				%div= f.submit "Log in", class:"button"
			/ = render "devise/shared/links"
			%a.close-reveal-modal ×


		= javascript_include_tag "//www.google.com/jsapi", "chartkick"
		- if flash[:notice]
			.notice= flash[:notice]
		= yield
		/ DataTables CSS
		%link{:href => "/DataTables-1.10.0/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
		/ jQuery
		%script{:charset => "utf8", :src => "/DataTables-1.10.0/js/jquery.js", :type => "text/javascript"}
		/ DataTables
		%script{:charset => "utf8", :src => "/DataTables-1.10.0/js/jquery.dataTables.js", :type => "text/javascript"}
		= javascript_include_tag "application"